# Generated by Django 5.2.12 on 2026-03-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_hospital_beds_count_hospital_international_patients'),
        ('inquiries', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
        ),
    ]
