# Generated by Django 5.2.12 on 2026-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_inquiry_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='needs_concierge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='needs_travel_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='needs_visa_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='service_fees_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUOTE_SENT', 'Quote Sent'), ('CONFIRMED', 'Confirmed'), ('PAYMENT_LINK_SENT', 'Payment Link Sent'), ('COMPLETED', 'Completed')], default='NEW', max_length=20),
        ),
    ]
