# Generated by Django 5.0.1 on 2026-04-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_inquiry_commission_amount_inquiry_needs_concierge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='treatment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
