# Generated by Django 5.0.1 on 2026-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_inquiry_treatment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='sittings',
            field=models.CharField(choices=[('1', '1 Sitting'), ('MULTIPLE', 'Multiple Sittings')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUOTE_SENT', 'Quote Sent'), ('CONFIRMED', 'Confirmed'), ('PAYMENT_LINK_SENT', 'Payment Link Sent'), ('COMPLETED', 'Completed'), ('CANCELLED_REFUNDED', 'Cancelled & Refunded')], default='NEW', max_length=20),
        ),
    ]
