# Generated by Django 5.0.1 on 2026-05-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_inquiry_sittings_alter_inquiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='sittings',
        ),
        migrations.AddField(
            model_name='quote',
            name='sittings',
            field=models.CharField(choices=[('1', '1 Sitting'), ('MULTIPLE', 'Multiple Sittings')], default='1', max_length=20),
        ),
    ]
