# Generated by Django 5.0.1 on 2026-05-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0009_remove_inquiry_sittings_quote_sittings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='sittings',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='current_sitting_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUOTE_SENT', 'Quote Sent'), ('CONFIRMED', 'Confirmed'), ('PAYMENT_LINK_SENT', 'Payment Link Sent'), ('AWAITING_NEXT_SITTING', 'Awaiting Next Sitting'), ('COMPLETED', 'Completed'), ('CANCELLED_REFUNDED', 'Cancelled & Refunded')], default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='QuoteSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to='inquiries.quote')),
            ],
        ),
    ]
