# Generated by Django 5.0.1 on 2026-05-16 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0010_remove_quote_sittings_inquiry_current_sitting_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
