# Generated by Django 5.0.1 on 2026-05-16 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0011_inquiry_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
