# Generated by Django 5.0.1 on 2026-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0012_alter_inquiry_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
