# Generated by Django 5.0.1 on 2026-07-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0015_inquirymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='booking_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='commission_payment_link_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('FULL', 'Fully Paid')], default='UNPAID', max_length=10),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, upload_to='travel_tickets/'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='ticket_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
