# Generated by Django 5.0.1 on 2026-08-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0016_inquiry_booking_confirmed_inquiry_commission_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='quote_attachments/'),
        ),
    ]
