# Generated by Django 5.0.1 on 2026-08-22 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0022_remove_hospital_wallet_balance_and_more'),
        ('inquiries', '0017_quote_attachment'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('TREATMENT', 'Treatment'), ('COMMISSION', 'Commission'), ('SUBSCRIPTION', 'Subscription')], default='TREATMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquiries.inquiry'),
        ),
        migrations.CreateModel(
            name='PayPalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_subscription_id', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_subscriptions', to='hospitals.hospital')),
            ],
        ),
    ]
