# Generated by Django 5.2.12 on 2026-03-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentPackage',
        ),
    ]
