# Generated by Django 5.0.1 on 2026-04-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Mexico', 'Mexico'), ('UAE', 'United Arab Emirates'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Spain', 'Spain'), ('Brazil', 'Brazil'), ('Germany', 'Germany'), ('USA', 'United States'), ('UK', 'United Kingdom'), ('Australia', 'Australia'), ('Canada', 'Canada'), ('France', 'France'), ('Jordan', 'Jordan'), ('Costa Rica', 'Costa Rica'), ('South Korea', 'South Korea'), ('South Africa', 'South Africa'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Other', 'Other')], max_length=100),
        ),
    ]
