# Generated by Django 5.0.1 on 2026-05-09 15:01

import django.db.models.deletion
from django.db import migrations, models

def populate_and_migrate_countries(apps, schema_editor):
    Country = apps.get_model('accounts', 'Country')
    User = apps.get_model('accounts', 'User')
    
    choices = [
        ('India', 'India'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'),
        ('Mexico', 'Mexico'), ('UAE', 'United Arab Emirates'), ('Singapore', 'Singapore'),
        ('Malaysia', 'Malaysia'), ('Spain', 'Spain'), ('Brazil', 'Brazil'),
        ('Germany', 'Germany'), ('USA', 'United States'), ('UK', 'United Kingdom'),
        ('Australia', 'Australia'), ('Canada', 'Canada'), ('France', 'France'),
        ('Jordan', 'Jordan'), ('Costa Rica', 'Costa Rica'), ('South Korea', 'South Korea'),
        ('South Africa', 'South Africa'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'),
        ('Hungary', 'Hungary'), ('Other', 'Other'),
    ]
    
    country_map = {}
    for code, name in choices:
        c, _ = Country.objects.get_or_create(name=name)
        country_map[code] = c
        country_map[name] = c
        
    for user in User.objects.all():
        if user.country_old:
            # Since country was a CharField with choices, it might store 'India' or 'USA' etc.
            country_obj = country_map.get(user.country_old)
            if country_obj:
                user.country = country_obj
                user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        # Step 1: Rename old country field
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='country_old',
        ),
        # Step 2: Add new ForeignKey field
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country'),
        ),
        # Step 3: Run the data migration
        migrations.RunPython(populate_and_migrate_countries),
        # Step 4: Remove the old field
        migrations.RemoveField(
            model_name='user',
            name='country_old',
        ),
    ]
