# Generated by Django 5.0.1 on 2026-04-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Treatments', 'Treatments'), ('Country Guides', 'Country Guides'), ('Health Tips', 'Health Tips'), ('Patient Stories', 'Patient Stories')], default='Treatments', max_length=50),
        ),
    ]
