# Generated by Django 5.0.1 on 2026-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='submitted_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
