# Generated by Django 5.2.12 on 2026-03-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('hospitals', '0005_treatmentpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
            preserve_default=False,
        ),
    ]
