# Generated by Django 5.2.12 on 2026-03-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_remove_hospital_website_hospital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name',
        ),
    ]
