# Generated by Django 5.2.12 on 2026-03-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_remove_hospital_country_remove_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(default='Unknown', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
