# Generated by Django 5.2.12 on 2026-03-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_treatmentpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentpackage',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.doctor'),
            preserve_default=False,
        ),
    ]
