# Generated by Django 5.2.12 on 2026-03-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_treatmentpackage_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='hospital_certificates/'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='accreditation',
            field=models.CharField(blank=True, choices=[('', 'Not Set'), ('JCI', 'JCI (Joint Commission International)'), ('NABH', 'NABH (National Accreditation Board)'), ('ISO', 'ISO 9001 Certified'), ('JACHO', 'JACHO Accredited'), ('OTHER', 'Other')], default='', max_length=200),
        ),
    ]
