# Generated by Django 5.2.12 on 2026-03-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='beds_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='international_patients',
            field=models.IntegerField(default=1000),
        ),
    ]
