# Generated by Django 5.2.12 on 2026-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_hospital_beds_count_hospital_international_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='subscription_plan',
            field=models.CharField(choices=[('BASIC', 'Basic (Free)'), ('PREMIUM', 'Premium ($199/mo)'), ('ELITE', 'Elite ($499/mo)')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
