# Generated by Django 5.2.12 on 2026-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_hospital_is_featured_hospital_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
