# Generated by Django 5.2.12 on 2026-03-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0012_alter_doctor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='suspension_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ReapprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='reapproval_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reapproval_requests', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
