# Generated by Django 5.0.1 on 2026-04-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0013_hospital_suspension_reason_alter_hospital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
    ]
