# Generated by Django 5.0.1 on 2026-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0015_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
