# Generated by Django 5.0.1 on 2026-04-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0016_treatmentpackage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('BASIC', 'Basic (Free)'), ('PREMIUM', 'Premium'), ('ELITE', 'Elite Executive')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_packages', models.IntegerField(default=5, help_text='-1 means unlimited')),
                ('commission_free_leads', models.IntegerField(default=0)),
                ('ranking_bonus', models.IntegerField(default=0)),
                ('display_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
