# Generated by Django 5.0.1 on 2026-04-20 03:52

from django.db import migrations

def create_defaults(apps, schema_editor):
    SubscriptionPlanConfig = apps.get_model('hospitals', 'SubscriptionPlanConfig')
    SubscriptionPlanConfig.objects.get_or_create(
        plan_type='BASIC',
        defaults={
            'price': 0.00,
            'max_packages': 5,
            'commission_free_leads': 0,
            'ranking_bonus': 0,
            'display_title': 'Basic (Free)',
            'description': 'Standard entry tier.'
        }
    )
    SubscriptionPlanConfig.objects.get_or_create(
        plan_type='PREMIUM',
        defaults={
            'price': 199.00,
            'max_packages': 25,
            'commission_free_leads': 0,
            'ranking_bonus': 2,
            'display_title': 'Premium ($199/mo)',
            'description': 'Advanced features and priority support.'
        }
    )
    SubscriptionPlanConfig.objects.get_or_create(
        plan_type='ELITE',
        defaults={
            'price': 499.00,
            'max_packages': -1,  # -1 means unlimited
            'commission_free_leads': 5,
            'ranking_bonus': 3,
            'display_title': 'Elite ($499/mo)',
            'description': 'Unlimited access and top ranking.'
        }
    )

def reverse_defaults(apps, schema_editor):
    SubscriptionPlanConfig = apps.get_model('hospitals', 'SubscriptionPlanConfig')
    SubscriptionPlanConfig.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0017_subscriptionplanconfig'),
    ]

    operations = [
        migrations.RunPython(create_defaults, reverse_defaults),
    ]
