# Generated by Django 5.0.1 on 2026-04-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0018_populate_default_subscription_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='last_admin_notification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
