# Generated by Django 5.0.1 on 2026-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0019_hospital_last_admin_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentpackage',
            name='sittings_required',
            field=models.IntegerField(default=1),
        ),
    ]
