# Generated by Django 5.0.1 on 2026-08-22 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0021_accreditation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='hospital',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('COMMISSION_FEE', 'Commission Fee'), ('SUBSCRIPTION', 'Subscription Fee'), ('TREATMENT_PAYMENT', 'Treatment Payment')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('paypal_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
